sudo: required

services:
  - docker

language: go
go:
  - 1.8
  - 1.9

env:
  matrix:
    - GOARCH=amd64 OSARCH=amd64
    - GOARCH=386 OSARCH=i386
  global:
    - VERSION=${TRAVIS_TAG}
    - VERSION=0.0.19
    - USER=${TRAVIS_REPO_SLUG%/*}
    - APP=${TRAVIS_REPO_SLUG#*/}
    - BT_SUBJECT=${USER}
    - BT_REPO_DEB=${APP}
    - secure: OdrfCMHcIrnlTT3WTubTMklx2b00U9nKDQe0aTjRDkNCNB0nB/fTvvIhhJ8+LDChcBcl0SBiy7Ok/pOEqlvreT1ri+XrPyXQq00sIz7qclxAsPcWsDQiFu8s1R3xuTc/7UG4e8V+WQOFf8bz5Hz1+tlgpHGINKidKQ6eMtFXJE1yLU7ZIyu27cumfdVgcYbBa9ut7h9oqc8VHT43/KM90BXE9mEtoisZnj1jeayZHfYNhr/WbMpj+39rkb50RMnPl+oQBEAL1Jovh0gINcCfQPdRDDlgKhSqaSFpvVWS1w2LlXcxYfbdhhtKkHGJ3ilUfWRHIGFyE1yQKbAL5SEUYPNkwdXF15uP+S0M9wmsQ5Tl48qgzJK+PbMQklc66EXobEPE8kvDiLxX3uHPLwUCR75H5Q6+3HEvEh9v7V46BNHHBS0uElq0kjr5/vYuYvljxf/hWWmZf8UbAYqV84UqwqPicmOB0ec7UJj4Ug9nF8H10bxOLDNiSl1Z+0Ha6LmO1kCRRTv4l5Yc+z21/eXGUq/h18r9ilY6KKoL3Cvlczx4uj4H4S4+46ww28cMlKYlKkoJNuwoFCqa4y4zlYmWHjDuc0rFro+cCaQ0FG3pl1szCEIh1NGcSlBFlrmzkquZop6M4S5wfWsH+zmYlaFTZ1tufo6lnaf8J008pWL6Ok8=

before_install:
  - sudo add-apt-repository 'deb https://dl.bintray.com/bincrafters/public-deb unstable main'
  - sudo apt-get -qq update
  - sudo apt-get install changelog
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh

install:
  - cd $GOPATH/src/github.com/$TRAVIS_REPO_SLUG
  - glide install
  - go install

script:
  - mkdir -p build/$OSARCH
  - GOOS=linux GOARCH=$GOARCH go build --ldflags "-X main.VERSION=$VERSION" -o build/$OSARCH/$APP main.go
  - go-bin-deb generate --file deb.json -a $OSARCH --version $VERSION -o $APP-$OSARCH-$VERSION.deb

deploy:
  - provider: releases
    api_key:
      secure: H64/VU6sWHdR4q6jo1C6vVuENALn6vWLi36MRKdhnLfcHBHDnSPCEcf3L5kUYHpAksMTKigofWYAEjyEVhzCm7CI1YHR3F4JRH6MUw/0jqoE5Nm5Ms6v8siIRdhWA+2e+Fg6CTDBfEV5FHLHEVTW3wSCyMz4g4U03aUfP5bz9g2SqLp3mwR0iPQmBkLzgDp8ju5tG25aTNSJC2eU/RGSC4CF7ZW7Z1/DB0p9ufbNxWiEpR7HwrwXCwS9lys9V/D+rWecu9BUinqfUgaYAsUHEKwns5FwYsTymFBRwYGif846/WPFOI/sDQFoyhHH9K23mHVYm3c5aRvKUqRMNbV2sRudCvI9Fl4FUlPO06jw7rhzM8ubHYn039pqE2wvPYYvKVmWudWayrdvlcKyz4eI3o4X1Cth0Owb+rXMXTsiSjOpIAiiLGjCrzfD/wfTJwANn/6Y22l6vqXfxQQjt43Q1wD7m50wDss2wXL8SdfeLBCioA3AHq3zMMUAsXA0rpC5q7Wl0wo5BaWatBO/VCmHIIIaZWA0tcQOJppwfSeq2GhgU+GIklJUifZwbuwd/OWzcbHJxSqc3quqMGzGTrklBHRHYWjkmRlFU1SycxizuhtEika6oO2H/WXPHfpLYBRCQtQEznPdviTpHQs3rL8YoHATUD2tKcOEWEoilL/fLo0=
    file_glob: true
    file:
      - $APP-386.deb
      - $APP-amd64.deb
      - $APP-386.rpm
      - $APP-amd64.rpm
    on:
      tags: false
    skip_cleanup: true
  - provider: bintray
    api_key:
      secure: I6A4/FnOVgtONv1Cvy9soIH4f+gfuXSqvE6JqGwwerjcK8Fcl1LebDy2ipcK8j9EoYlJZ88Vh1/Vf6Z1L7+eV1Lc9PfKOJOSkAq4gr4vAb4rdO8L+M/ZTw+LH88Cu6J64Q6Hkx1aKDiTHCZbaVc8QeTH6zob1clSvx8h7oCz81N3VY25QvhiB2/eAh4NKBYN/9yz1TgTVYu3fNvF24tNewcH+56HBZm5d4uDnfDrAhgLGBJCqhxXpnQh2ALiQeqEgmyGwslcGCQ4bAL3cx7HgrkEdpoFusisoNOs11G6+yhiwjFyNNE/obwbMlV1teZ1JpjZicPTG7o5CEXD6/UKez4nwQsa4veNxlPAU7hU2GcnVJvCWmzzQjNuDUkVv5q+McTQA82sGrFkYxUFHkQfHoqvLRNANuMRiY14isoT2chzIK/YhsB2BJnWqooB0OGqda30DQu8Ir8Ro9K++5NoqgdWpilY5LWhko8Sd72KiUmI/wgiU8UHUZ0lxEePL1rn8wi8QOhnaPQ7SYhWwuvMoyMG1zt15PUCa9ya/ugYDlquj+zGFX3D/AhaEUT4hEhRGz3Lng1rqH1QmpHj4yAAgIzmdxiXbTOuess4i9QzzUlMNugiw/c51GVpI4ypC/8h/7xHEfqugX/e+GMIORdk6vb+eJp3u5TJB2mWrrx9BKw=
    file_glob: true
    file:
      - $APP-386.deb
      - $APP-amd64.deb
      - $APP-386.rpm
      - $APP-amd64.rpm
    on:
      tags: false
    skip_cleanup: true
